apiVersion: v1
kind: Namespace
metadata:
  name: automaton
  labels:
    name: automaton
    app: automaton-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: automaton-monitoring
  labels:
    name: automaton-monitoring
    app: automaton-monitoring